use crate::models::*;

pub const PATTERNS: &'static [Pattern] = &[
    Pattern::simple_replace("psh", "পশ"),
    Pattern::simple_replace("bhl", "ভ্ল"),
    Pattern::simple_replace("bdh", "ব্ধ"),
    Pattern::simple_replace("bj", "ব্জ"),
    Pattern::simple_replace("bd", "ব্দ"),
    Pattern::simple_replace("bb", "ব্ব"),
    Pattern::simple_replace("bl", "ব্ল"),
    Pattern::simple_replace("bh", "ভ"),
    Pattern::simple_replace("vl", "ভ্ল"),
    Pattern::simple_replace("b", "ব"),
    Pattern::simple_replace("v", "ভ"),
    Pattern::simple_replace("cNG", "চ্ঞ"),
    Pattern::simple_replace("cch", "চ্ছ"),
    Pattern::simple_replace("cc", "চ্চ"),
    Pattern::simple_replace("ch", "ছ"),
    Pattern::simple_replace("c", "চ"),
    Pattern::simple_replace("dhn", "ধ্ন"),
    Pattern::simple_replace("dhm", "ধ্ম"),
    Pattern::simple_replace("dgh", "দ্ঘ"),
    Pattern::simple_replace("ddh", "দ্ধ"),
    Pattern::simple_replace("dbh", "দ্ভ"),
    Pattern::simple_replace("dv", "দ্ভ"),
    Pattern::simple_replace("dm", "দ্ম"),
    Pattern::simple_replace("DD", "ড্ড"),
    Pattern::simple_replace("Dh", "ঢ"),
    Pattern::simple_replace("dh", "ধ"),
    Pattern::simple_replace("dg", "দ্গ"),
    Pattern::simple_replace("dd", "দ্দ"),
    Pattern::simple_replace("D", "ড"),
    Pattern::simple_replace("d", "দ"),
    Pattern::simple_replace("...", "..."),
    Pattern::simple_replace(".`", "."),
    Pattern::simple_replace("..", "।।"),
    Pattern::simple_replace(".", "।"),
    Pattern::simple_replace("ghn", "ঘ্ন"),
    Pattern::simple_replace("Ghn", "ঘ্ন"),
    Pattern::simple_replace("gdh", "গ্ধ"),
    Pattern::simple_replace("Gdh", "গ্ধ"),
    Pattern::simple_replace("gN", "গ্ণ"),
    Pattern::simple_replace("GN", "গ্ণ"),
    Pattern::simple_replace("gn", "গ্ন"),
    Pattern::simple_replace("Gn", "গ্ন"),
    Pattern::simple_replace("gm", "গ্ম"),
    Pattern::simple_replace("Gm", "গ্ম"),
    Pattern::simple_replace("gl", "গ্ল"),
    Pattern::simple_replace("Gl", "গ্ল"),
    Pattern::simple_replace("gg", "জ্ঞ"),
    Pattern::simple_replace("GG", "জ্ঞ"),
    Pattern::simple_replace("Gg", "জ্ঞ"),
    Pattern::simple_replace("gG", "জ্ঞ"),
    Pattern::simple_replace("gh", "ঘ"),
    Pattern::simple_replace("Gh", "ঘ"),
    Pattern::simple_replace("g", "গ"),
    Pattern::simple_replace("G", "গ"),
    Pattern::simple_replace("hN", "হ্ণ"),
    Pattern::simple_replace("hn", "হ্ন"),
    Pattern::simple_replace("hm", "হ্ম"),
    Pattern::simple_replace("hl", "হ্ল"),
    Pattern::simple_replace("h", "হ"),
    Pattern::simple_replace("jjh", "জ্ঝ"),
    Pattern::simple_replace("jNG", "জ্ঞ"),
    Pattern::simple_replace("jh", "ঝ"),
    Pattern::simple_replace("jj", "জ্জ"),
    Pattern::simple_replace("j", "জ"),
    Pattern::simple_replace("J", "জ"),
    Pattern::simple_replace("kkhN", "ক্ষ্ণ"),
    Pattern::simple_replace("kShN", "ক্ষ্ণ"),
    Pattern::simple_replace("kkhm", "ক্ষ্ম"),
    Pattern::simple_replace("kShm", "ক্ষ্ম"),
    Pattern::simple_replace("kxN", "ক্ষ্ণ"),
    Pattern::simple_replace("kxm", "ক্ষ্ম"),
    Pattern::simple_replace("kkh", "ক্ষ"),
    Pattern::simple_replace("kSh", "ক্ষ"),
    Pattern::simple_replace("ksh", "কশ"),
    Pattern::simple_replace("kx", "ক্ষ"),
    Pattern::simple_replace("kk", "ক্ক"),
    Pattern::simple_replace("kT", "ক্ট"),
    Pattern::simple_replace("kt", "ক্ত"),
    Pattern::simple_replace("kl", "ক্ল"),
    Pattern::simple_replace("ks", "ক্স"),
    Pattern::simple_replace("kh", "খ"),
    Pattern::simple_replace("k", "ক"),
    Pattern::simple_replace("lbh", "ল্ভ"),
    Pattern::simple_replace("ldh", "ল্ধ"),
    Pattern::simple_replace("lkh", "লখ"),
    Pattern::simple_replace("lgh", "লঘ"),
    Pattern::simple_replace("lph", "লফ"),
    Pattern::simple_replace("lk", "ল্ক"),
    Pattern::simple_replace("lg", "ল্গ"),
    Pattern::simple_replace("lT", "ল্ট"),
    Pattern::simple_replace("lD", "ল্ড"),
    Pattern::simple_replace("lp", "ল্প"),
    Pattern::simple_replace("lv", "ল্ভ"),
    Pattern::simple_replace("lm", "ল্ম"),
    Pattern::simple_replace("ll", "ল্ল"),
    Pattern::simple_replace("lb", "ল্ব"),
    Pattern::simple_replace("l", "ল"),
    Pattern::simple_replace("mth", "ম্থ"),
    Pattern::simple_replace("mph", "ম্ফ"),
    Pattern::simple_replace("mbh", "ম্ভ"),
    Pattern::simple_replace("mpl", "মপ্ল"),
    Pattern::simple_replace("mn", "ম্ন"),
    Pattern::simple_replace("mp", "ম্প"),
    Pattern::simple_replace("mv", "ম্ভ"),
    Pattern::simple_replace("mm", "ম্ম"),
    Pattern::simple_replace("ml", "ম্ল"),
    Pattern::simple_replace("mb", "ম্ব"),
    Pattern::simple_replace("mf", "ম্ফ"),
    Pattern::simple_replace("m", "ম"),
    Pattern::simple_replace("0", "০"),
    Pattern::simple_replace("1", "১"),
    Pattern::simple_replace("2", "২"),
    Pattern::simple_replace("3", "৩"),
    Pattern::simple_replace("4", "৪"),
    Pattern::simple_replace("5", "৫"),
    Pattern::simple_replace("6", "৬"),
    Pattern::simple_replace("7", "৭"),
    Pattern::simple_replace("8", "৮"),
    Pattern::simple_replace("9", "৯"),
    Pattern::simple_replace("NgkSh", "ঙ্ক্ষ"),
    Pattern::simple_replace("Ngkkh", "ঙ্ক্ষ"),
    Pattern::simple_replace("NGch", "ঞ্ছ"),
    Pattern::simple_replace("Nggh", "ঙ্ঘ"),
    Pattern::simple_replace("Ngkh", "ঙ্খ"),
    Pattern::simple_replace("NGjh", "ঞ্ঝ"),
    Pattern::simple_replace("ngOU", "ঙ্গৌ"),
    Pattern::simple_replace("ngOI", "ঙ্গৈ"),
    Pattern::simple_replace("Ngkx", "ঙ্ক্ষ"),
    Pattern::simple_replace("NGc", "ঞ্চ"),
    Pattern::simple_replace("nch", "ঞ্ছ"),
    Pattern::simple_replace("njh", "ঞ্ঝ"),
    Pattern::simple_replace("ngh", "ঙ্ঘ"),
    Pattern::simple_replace("Ngk", "ঙ্ক"),
    Pattern::simple_replace("Ngx", "ঙ্ষ"),
    Pattern::simple_replace("Ngg", "ঙ্গ"),
    Pattern::simple_replace("Ngm", "ঙ্ম"),
    Pattern::simple_replace("NGj", "ঞ্জ"),
    Pattern::simple_replace("ndh", "ন্ধ"),
    Pattern::simple_replace("nTh", "ন্ঠ"),
    Pattern::simple_replace("NTh", "ণ্ঠ"),
    Pattern::simple_replace("nth", "ন্থ"),
    Pattern::simple_replace("nkh", "ঙ্খ"),
    Pattern::simple_replace("ngo", "ঙ্গ"),
    Pattern::simple_replace("nga", "ঙ্গা"),
    Pattern::simple_replace("ngi", "ঙ্গি"),
    Pattern::simple_replace("ngI", "ঙ্গী"),
    Pattern::simple_replace("ngu", "ঙ্গু"),
    Pattern::simple_replace("ngU", "ঙ্গূ"),
    Pattern::simple_replace("nge", "ঙ্গে"),
    Pattern::simple_replace("ngO", "ঙ্গো"),
    Pattern::simple_replace("NDh", "ণ্ঢ"),
    Pattern::simple_replace("nsh", "নশ"),
    Pattern::simple_replace("Ngr", "ঙর"),
    Pattern::simple_replace("NGr", "ঞর"),
    Pattern::simple_replace("ngr", "ংর"),
    Pattern::simple_replace("nj", "ঞ্জ"),
    Pattern::simple_replace("Ng", "ঙ"),
    Pattern::simple_replace("NG", "ঞ"),
    Pattern::simple_replace("nk", "ঙ্ক"),
    Pattern::simple_replace("ng", "ং"),
    Pattern::simple_replace("nn", "ন্ন"),
    Pattern::simple_replace("NN", "ণ্ণ"),
    Pattern::simple_replace("Nn", "ণ্ন"),
    Pattern::simple_replace("nm", "ন্ম"),
    Pattern::simple_replace("Nm", "ণ্ম"),
    Pattern::simple_replace("nd", "ন্দ"),
    Pattern::simple_replace("nT", "ন্ট"),
    Pattern::simple_replace("NT", "ণ্ট"),
    Pattern::simple_replace("nD", "ন্ড"),
    Pattern::simple_replace("ND", "ণ্ড"),
    Pattern::simple_replace("nt", "ন্ত"),
    Pattern::simple_replace("ns", "ন্স"),
    Pattern::simple_replace("nc", "ঞ্চ"),
    Pattern::simple_replace("n", "ন"),
    Pattern::simple_replace("N", "ণ"),
    Pattern::simple_replace("OI`", "ৈ"),
    Pattern::simple_replace("OU`", "ৌ"),
    Pattern::simple_replace("O`", "ো"),
    Pattern {
        find: "OI",
        default_replace: "ৈ",
        rules: &[
            Rule {
                matches: &[Match::PrefixNot(MatchType::Consonant)],
                replace: "ঐ",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "ঐ",
            },
        ],
    },
    Pattern {
        find: "OU",
        default_replace: "ৌ",
        rules: &[
            Rule {
                matches: &[Match::PrefixNot(MatchType::Consonant)],
                replace: "ঔ",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "ঔ",
            },
        ],
    },
    Pattern {
        find: "O",
        default_replace: "ো",
        rules: &[
            Rule {
                matches: &[Match::PrefixNot(MatchType::Consonant)],
                replace: "ও",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "ও",
            },
        ],
    },
    Pattern::simple_replace("phl", "ফ্ল"),
    Pattern::simple_replace("pT", "প্ট"),
    Pattern::simple_replace("pt", "প্ত"),
    Pattern::simple_replace("pn", "প্ন"),
    Pattern::simple_replace("pp", "প্প"),
    Pattern::simple_replace("pl", "প্ল"),
    Pattern::simple_replace("ps", "প্স"),
    Pattern::simple_replace("ph", "ফ"),
    Pattern::simple_replace("fl", "ফ্ল"),
    Pattern::simple_replace("f", "ফ"),
    Pattern::simple_replace("p", "প"),
    Pattern::simple_replace("rri`", "ৃ"),
    Pattern {
        find: "rri",
        default_replace: "ৃ",
        rules: &[
            Rule {
                matches: &[Match::PrefixNot(MatchType::Consonant)],
                replace: "ঋ",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "ঋ",
            },
        ],
    },
    Pattern::simple_replace("rrZ", "রর‍্য"),
    Pattern::simple_replace("rry", "রর‍্য"),
    Pattern {
        find: "rZ",
        default_replace: "র‍্য",
        rules: &[Rule {
            matches: &[
                Match::Prefix(MatchType::Consonant),
                Match::PrefixNot(MatchType::Exact('r')),
                Match::PrefixNot(MatchType::Exact('y')),
                Match::PrefixNot(MatchType::Exact('w')),
                Match::PrefixNot(MatchType::Exact('x')),
            ],
            replace: "্র্য",
        }],
    },
    Pattern {
        find: "ry",
        default_replace: "র‍্য",
        rules: &[Rule {
            matches: &[
                Match::Prefix(MatchType::Consonant),
                Match::PrefixNot(MatchType::Exact('r')),
                Match::PrefixNot(MatchType::Exact('y')),
                Match::PrefixNot(MatchType::Exact('w')),
                Match::PrefixNot(MatchType::Exact('x')),
            ],
            replace: "্র্য",
        }],
    },
    Pattern {
        find: "rr",
        default_replace: "রর",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Vowel),
                    Match::SuffixNot(MatchType::Exact('r')),
                    Match::SuffixNot(MatchType::Punctuation),
                ],
                replace: "র্",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Consonant),
                    Match::PrefixNot(MatchType::Exact('r')),
                ],
                replace: "্রর",
            },
        ],
    },
    Pattern::simple_replace("Rg", "ড়্গ"),
    Pattern::simple_replace("Rh", "ঢ়"),
    Pattern::simple_replace("R", "ড়"),
    Pattern {
        find: "r",
        default_replace: "র",
        rules: &[Rule {
            matches: &[
                Match::Prefix(MatchType::Consonant),
                Match::PrefixNot(MatchType::Exact('r')),
                Match::PrefixNot(MatchType::Exact('y')),
                Match::PrefixNot(MatchType::Exact('w')),
                Match::PrefixNot(MatchType::Exact('x')),
                Match::PrefixNot(MatchType::Exact('Z')),
            ],
            replace: "্র",
        }],
    },
    Pattern::simple_replace("shch", "শ্ছ"),
    Pattern::simple_replace("ShTh", "ষ্ঠ"),
    Pattern::simple_replace("Shph", "ষ্ফ"),
    Pattern::simple_replace("Sch", "শ্ছ"),
    Pattern::simple_replace("skl", "স্ক্ল"),
    Pattern::simple_replace("skh", "স্খ"),
    Pattern::simple_replace("sth", "স্থ"),
    Pattern::simple_replace("sph", "স্ফ"),
    Pattern::simple_replace("shc", "শ্চ"),
    Pattern::simple_replace("sht", "শ্ত"),
    Pattern::simple_replace("shn", "শ্ন"),
    Pattern::simple_replace("shm", "শ্ম"),
    Pattern::simple_replace("shl", "শ্ল"),
    Pattern::simple_replace("Shk", "ষ্ক"),
    Pattern::simple_replace("ShT", "ষ্ট"),
    Pattern::simple_replace("ShN", "ষ্ণ"),
    Pattern::simple_replace("Shp", "ষ্প"),
    Pattern::simple_replace("Shf", "ষ্ফ"),
    Pattern::simple_replace("Shm", "ষ্ম"),
    Pattern::simple_replace("spl", "স্প্ল"),
    Pattern::simple_replace("sk", "স্ক"),
    Pattern::simple_replace("Sc", "শ্চ"),
    Pattern::simple_replace("sT", "স্ট"),
    Pattern::simple_replace("st", "স্ত"),
    Pattern::simple_replace("sn", "স্ন"),
    Pattern::simple_replace("sp", "স্প"),
    Pattern::simple_replace("sf", "স্ফ"),
    Pattern::simple_replace("sm", "স্ম"),
    Pattern::simple_replace("sl", "স্ল"),
    Pattern::simple_replace("sh", "শ"),
    Pattern::simple_replace("Sc", "শ্চ"),
    Pattern::simple_replace("St", "শ্ত"),
    Pattern::simple_replace("Sn", "শ্ন"),
    Pattern::simple_replace("Sm", "শ্ম"),
    Pattern::simple_replace("Sl", "শ্ল"),
    Pattern::simple_replace("Sh", "ষ"),
    Pattern::simple_replace("s", "স"),
    Pattern::simple_replace("S", "শ"),
    Pattern::simple_replace("oo`", "ু"),
    Pattern {
        find: "oo",
        default_replace: "ু",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "উ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "উ",
            },
        ],
    },
    Pattern::simple_replace("o`", ""),
    Pattern::simple_replace("oZ", "অ্য"),
    Pattern {
        find: "o",
        default_replace: "",
        rules: &[
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Vowel),
                    Match::PrefixNot(MatchType::Exact('o')),
                ],
                replace: "ও",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Vowel),
                    Match::Prefix(MatchType::Exact('o')),
                ],
                replace: "অ",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "অ",
            },
        ],
    },
    Pattern::simple_replace("tth", "ত্থ"),
    Pattern::simple_replace("t``", "ৎ"),
    Pattern::simple_replace("TT", "ট্ট"),
    Pattern::simple_replace("Tm", "ট্ম"),
    Pattern::simple_replace("Th", "ঠ"),
    Pattern::simple_replace("tn", "ত্ন"),
    Pattern::simple_replace("tm", "ত্ম"),
    Pattern::simple_replace("th", "থ"),
    Pattern::simple_replace("tt", "ত্ত"),
    Pattern::simple_replace("T", "ট"),
    Pattern::simple_replace("t", "ত"),
    Pattern::simple_replace("aZ", "অ্যা"),
    Pattern::simple_replace("AZ", "অ্যা"),
    Pattern::simple_replace("a`", "া"),
    Pattern::simple_replace("A`", "া"),
    Pattern {
        find: "a",
        default_replace: "া",
        rules: &[
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "আ",
            },
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::PrefixNot(MatchType::Exact('a')),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "য়া",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Exact('a')),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "আ",
            },
        ],
    },
    Pattern::simple_replace("i`", "ি"),
    Pattern {
        find: "i",
        default_replace: "ি",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ই",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ই",
            },
        ],
    },
    Pattern::simple_replace("I`", "ী"),
    Pattern {
        find: "I",
        default_replace: "ী",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঈ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঈ",
            },
        ],
    },
    Pattern::simple_replace("u`", "ু"),
    Pattern {
        find: "u",
        default_replace: "ু",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "উ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "উ",
            },
        ],
    },
    Pattern::simple_replace("U`", "ূ"),
    Pattern {
        find: "U",
        default_replace: "ূ",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঊ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঊ",
            },
        ],
    },
    Pattern::simple_replace("ee`", "ী"),
    Pattern {
        find: "ee",
        default_replace: "ী",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঈ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "ঈ",
            },
        ],
    },
    Pattern::simple_replace("e`", "ে"),
    Pattern {
        find: "e",
        default_replace: "ে",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "এ",
            },
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::SuffixNot(MatchType::Exact('`')),
                ],
                replace: "এ",
            },
        ],
    },
    Pattern::simple_replace("z", "য"),
    Pattern::simple_replace("Z", "্য"),
    Pattern {
        find: "y",
        default_replace: "্য",
        rules: &[
            Rule {
                matches: &[
                    Match::PrefixNot(MatchType::Consonant),
                    Match::PrefixNot(MatchType::Punctuation),
                ],
                replace: "য়",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Punctuation)],
                replace: "ইয়",
            },
        ],
    },
    Pattern::simple_replace("Y", "য়"),
    Pattern::simple_replace("q", "ক"),
    Pattern {
        find: "w",
        default_replace: "ও",
        rules: &[
            Rule {
                matches: &[
                    Match::Prefix(MatchType::Punctuation),
                    Match::Suffix(MatchType::Vowel),
                ],
                replace: "ওয়",
            },
            Rule {
                matches: &[Match::Prefix(MatchType::Consonant)],
                replace: "্ব",
            },
        ],
    },
    Pattern {
        find: "x",
        default_replace: "ক্স",
        rules: &[Rule {
            matches: &[Match::Prefix(MatchType::Punctuation)],
            replace: "এক্স",
        }],
    },
    Pattern::simple_replace(":`", ":"),
    Pattern::simple_replace(":", "ঃ"),
    Pattern::simple_replace("^`", "^"),
    Pattern::simple_replace("^", "ঁ"),
    Pattern::simple_replace(",,", "্‌"),
    Pattern::simple_replace(",", ","),
    Pattern::simple_replace("$", "৳"),
    Pattern::simple_replace("`", ""),
];
